language: python

python:
  - "2.7"

env:
  - TOXENV=py26-1.2.X
  - TOXENV=py26-1.3.X
  - TOXENV=py26-1.4.X
  - TOXENV=py26-1.5.X,py32-1.5.X
  - TOXENV=py26-1.6.X,py32-1.6.X
  - TOXENV=py27-trunk,py32-trunk

install:
  - pip install tox --use-mirrors

script:
    - tox

branches:
  only:
    - master

matrix:
  allow_failures:
    - env: TOXENV=py27-trunk,py32-trunk